# Schema for the configuration files of the Bunny stream logger module.
bunny_stream_logger.settings:
  type: config_object
  label: 'Bunny stream logger settings'
  mapping:
    row_limit:
      type: integer
      label: 'Database log messages to keep'
